imaginerium/pages/characterList.js

Search character by name now working

search by name working

---

imaginerium/Components/CharacterCard.js
imaginerium/Components/CharacterPopUp.js
imaginerium/pages/characterList.js
imaginerium/pages/viewCharacter.js
imaginerium/styles/characterList.module.css
imaginerium/styles/globals.css

CSS on character cards fixed and minimal character pop up styling done.

View character css cleanup

---

imaginerium/modals/formSubmissionPopUp.js
imaginerium/pages/_document.js
imaginerium/pages/createCharacter.js
imaginerium/pages/index.js
imaginerium/styles/globals.css

Pop up on form submission and home page main button navigation complete

Form submission pop up

---

imaginerium/Components/DarkModeToggle.js
imaginerium/pages/_app.js
imaginerium/styles/Home.module.css
imaginerium/styles/globals.css

Dark mode functionality working but it needs to complete the dark styling in specific components

Dark mode functionality

---

imaginerium/Components/CharacterCard.js
imaginerium/Components/CharacterPopUp.js
imaginerium/pages/characterList.js
imaginerium/styles/globals.css

View all button and editing functionality

More editing

---

imaginerium/cypress.config.js
imaginerium/cypress/e2e/spec.cy.js
imaginerium/cypress/fixtures/example.json
imaginerium/cypress/support/commands.js
imaginerium/cypress/support/e2e.js

Cypress testing to visit pages

Very very very basic tests

---

imaginerium/Components/Navigation.js
imaginerium/pages/createNewWorld.js
imaginerium/styles/navigation.module.css

Fixed a couple of things re button text and map height on screen

Logout button

---

imaginerium/Components/CharacterCard.js
imaginerium/Components/CharacterPopUp.js
imaginerium/pages/characterList.js
imaginerium/styles/globals.css

Popup alterations

---

imaginerium/Components/Step3.js

form fully working

---

imaginerium/Components/CharacterCard.js
imaginerium/pages/characterList.js
imaginerium/pages/dashboard.js
imaginerium/pages/sharedCharacters.js
imaginerium/pages/timeline.js
imaginerium/styles/Home.module.css
imaginerium/styles/characterList.module.css
imaginerium/styles/globals.css
imaginerium/styles/landing.module.css
imaginerium/styles/timeline.module.css

Character list styling
Timeline started
Collab started

Weekend iona

---

imaginerium/Components/DarkModeToggle.js
imaginerium/Components/Navigation.js
imaginerium/Components/login-btn.js
imaginerium/next.config.js
imaginerium/pages/characterList.js
imaginerium/styles/globals.css
imaginerium/styles/login-btn.module.css
imaginerium/styles/navigation.module.css

Navigation bar styled but Dark mode disabled due CSS issues (Code commented only)

Nav bar styled (dark mode disabled)

---

imaginerium/Components/CharacterCard.js
imaginerium/Components/Step1.js
imaginerium/Components/Step2.js
imaginerium/Components/blob.js
imaginerium/package-lock.json
imaginerium/package.json
imaginerium/styles/blob.module.css
imaginerium/styles/globals.css
imaginerium/styles/landing.module.css
imaginerium/styles/navigation.module.css
imaginerium/styles/steps.module.css

styling form

---

imaginerium/Components/Step1.js

added ref attribute to form tag

---

imaginerium/Components/Navigation.js
imaginerium/styles/globals.css

Fixed some issues in CSS globals

Fixing css

---

imaginerium/pages/aboutUs.js
imaginerium/pages/dashboard.js
imaginerium/styles/aboutUs.module.css
imaginerium/styles/globals.css

Fliss messing about

---

imaginerium/Components/CharacterCard.js
imaginerium/Components/CharacterPopUp.js
imaginerium/pages/sharedCharacters.js
imaginerium/styles/characterCard.module.css
imaginerium/styles/characterPopup.module.css
imaginerium/styles/globals.css

CSS on character cards and pop up fixed and moved into CSS modules

Character card fixing

---

imaginerium/Components/CharacterPopUp.js

moved position of 'edit' and 'done' buttons

buttons on popup

---

imaginerium/pages/dashboard.js

Dashboard buttons now links, and have correct text

Fixing dashboard buttons

---

imaginerium/Components/Form.js
imaginerium/Components/NewNavBar.js
imaginerium/styles/Home.module.css
imaginerium/styles/login-btn.module.css
imaginerium/styles/newNavBar.module.css

New nav bar

---

imaginerium/pages/aboutUs.js
imaginerium/pages/createNewWorld.js
imaginerium/styles/createNewWorld.module.css
imaginerium/styles/globals.css

Fixed About Us page, added world map css module, added margin to world map

Aboutusadditions

---

imaginerium/Components/PleaseLogin.js
imaginerium/pages/characterList.js
imaginerium/pages/createCharacter.js
imaginerium/pages/createNewWorld.js
imaginerium/pages/sharedCharacters.js
imaginerium/styles/pleaseLogin.module.css

Login if loggedout page

---

imaginerium/pages/createNewWorld.js

added import to createNewWorld page

---

imaginerium/pages/createCharacter.js

updated createCharacter page to have PleaseLogin and session

---

imaginerium/pages/createCharacter.js

removed double definition of session

---

imaginerium/Components/CharacterPopUp.js
imaginerium/styles/characterPopup.module.css
imaginerium/styles/globals.css

Initial pop up styling for usability

Popupstyling tuesday

---

imaginerium/Components/Step1.js
imaginerium/Components/Step2.js
imaginerium/Components/Step3.js

form fixed

---

imaginerium/Components/NoCharactersShared.js
imaginerium/Components/NoCharactersYet.js
imaginerium/pages/aboutUs.js
imaginerium/pages/characterList.js
imaginerium/pages/sharedCharacters.js
imaginerium/styles/aboutUs.module.css
imaginerium/styles/globals.css

Ready to merge - characters, about us, some global.css changes

You have no characters so make some

---

imaginerium/Components/NewNavBar.js
imaginerium/styles/newNavBar.module.css

added responsive css to navbar

added responsive css to navbar

---

imaginerium/pages/aboutUs.js
imaginerium/styles/createNewWorld.module.css
imaginerium/styles/globals.css
imaginerium/styles/login-btn.module.css

shifted sign out button and map to remove conflict

---

imaginerium/Components/NewNavBar.js
imaginerium/styles/newNavBar.module.css

added more links to navbar

---

imaginerium/Components/NoCharactersShared.js
imaginerium/Components/Step1.js
imaginerium/Components/Step2.js
imaginerium/Components/Step3.js
imaginerium/styles/steps.module.css

top margin fixed

---

imaginerium/pages/dashboard.js
imaginerium/styles/Home.module.css
imaginerium/styles/globals.css

Dashboard responsive design completed. Pending approval of the team.

Dashboard styling fix

---

imaginerium/pages/dashboard.js
imaginerium/styles/steps.module.css

styling and responsively for step 2

Step 2 styling

---

imaginerium/Components/Step1.js
imaginerium/styles/steps.module.css

styled form step3

---

imaginerium/Components/CharacterCard.js
imaginerium/Components/CharacterPopUp.js
imaginerium/styles/characterCard.module.css
imaginerium/styles/characterPopup.module.css
imaginerium/styles/globals.css

functionality improved for edit, still needs to be replicated

Moving button pop up

---

imaginerium/Components/CharacterPopUp.js
imaginerium/styles/characterPopup.module.css

Changed edit buttons to icons and moved location

Even more pop up

---

imaginerium/Components/login-btn.js
imaginerium/pages/dashboard.js
imaginerium/styles/Home.module.css
imaginerium/styles/login-btn.module.css

Dashboard main buttons and login/out out button pointer added
Responsive design on the dashboard page and login/log out container fixed

Dashboard pointer fix

---

imaginerium/Components/CharacterCard.js
imaginerium/pages/createNewWorld.js
imaginerium/styles/characterCard.module.css
imaginerium/styles/createNewWorld.module.css

Rea lcharacter card update

---

imaginerium/Components/DarkModeToggle.js
imaginerium/Components/Step1.js
imaginerium/Components/Step2.js
imaginerium/Components/Step3.js
imaginerium/Components/Switch.js
imaginerium/styles/globals.css
imaginerium/styles/newNavBar.module.css
imaginerium/styles/steps.module.css
imaginerium/styles/switch.module.css

form styled
added a new alive/dead switch
styled random button
changed m to cm
fixed navbar position

form styled and added a new alive/dead switch

---

imaginerium/pages/characterList.js
imaginerium/styles/characterList.module.css

Minor tweaks to Character List page

polishing finished

---

imaginerium/Components/SharedCharacterCard.js
imaginerium/Components/SharedCharacterPopUp.js
imaginerium/pages/characterList.js
imaginerium/pages/sharedCharacters.js

Shared page

---

imaginerium/Components/CharacterPopUp.js
imaginerium/Components/NoCharactersShared.js
imaginerium/Components/NoCharactersYet.js
imaginerium/Components/PleaseLogin.js
imaginerium/styles/characterPopup.module.css
imaginerium/styles/pleaseLogin.module.css

Styling on 'no characters/loggedin' components

Iona evening wednesday

---

imaginerium/pages/characterList.js

fixed bug in newest to oldest and oldest to newest search

---

imaginerium/Components/CharacterCard.js
imaginerium/Components/CharacterPopUp.js
imaginerium/pages/characterList.js

Aria labels and alt text added

Thursday iona

---

imaginerium/Components/login-btn.js
imaginerium/pages/dashboard.js
imaginerium/styles/login-btn.module.css

Nav bar alt image and size attribute on image component on dashboard fixed.

Dashboard accessibility fix

---

imaginerium/Components/login-btn.js

capitalised login/out button text

---

imaginerium/Components/CharacterCard.js
imaginerium/Components/CharacterPopUp.js
imaginerium/Components/PleaseLogin.js
imaginerium/Components/SharedCharacterCard.js
imaginerium/Components/SharedCharacterPopUp.js
imaginerium/pages/characterList.js
imaginerium/pages/index.js
imaginerium/pages/sharedCharacters.js
imaginerium/styles/characterPopup.module.css
imaginerium/styles/landing.module.css

- added media queries for landing page and character pop up
- changed some divs around to make more responsive
- added aria labels to character + shared character card + page
- added alt text to character images

Monday iona
